# Ultralytics ðŸš€ AGPL-3.0 License - https://ultralytics.com/license

name: ðŸ› Bug Report
# title: " "
description: Problems with Ultralytics YOLO Replicate deployment
labels: [bug, triage]
type: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an Ultralytics YOLO Replicate ðŸ› Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the Ultralytics [Docs](https://docs.ultralytics.com/) and [issues](https://github.com/ultralytics/replicate/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the Ultralytics Replicate [issues](https://github.com/ultralytics/replicate/issues) and found no similar bug report.
          required: true

  - type: dropdown
    attributes:
      label: Ultralytics Replicate Component
      description: |
        Please select the component where you found the bug.
      multiple: true
      options:
        - "Model Export"
        - "Local Testing"
        - "Cog Configuration"
        - "Replicate Deployment"
        - "GitHub Actions"
        - "YOLO11n Demo"
        - "Custom Model"
        - "Other"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug
      description: Please provide as much information as possible. Copy and paste console output and error messages including the _full_ traceback. Use [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to format text, code and logs. If necessary, include screenshots for visual elements only. Providing detailed information will help us resolve the issue more efficiently.
      placeholder: |
        ðŸ’¡ ProTip! Include as much information as possible (logs, tracebacks, screenshots, etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Please provide your system information and the output of `yolo checks` (CLI) or `ultralytics.utils.checks.collect_system_info()` (Python) command to help us diagnose the problem.
      placeholder: |
        Paste output of `yolo checks` (CLI) or `ultralytics.utils.checks.collect_system_info()` (Python) command, i.e.:
        ```
        Ultralytics 8.3.2 ðŸš€ Python-3.11.2 torch-2.4.1 CPU (Apple M3)
        Setup complete âœ… (8 CPUs, 16.0 GB RAM, 266.5/460.4 GB disk)

        OS                  macOS-13.5.2
        Environment         Terminal
        Python              3.11.2
        Install             pip
        RAM                 16.00 GB
        CPU                 Apple M3
        CUDA                None
        Cog                 0.9.0
        Docker              24.0.0
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimal reproducible example](https://docs.ultralytics.com/help/minimum-reproducible-example/).
      placeholder: |
        ```bash
        # Commands to reproduce your issue here
        cd yolo11n
        cog push r8.im/username/model
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/ultralytics/replicate/pulls) (PR) to help improve Ultralytics Replicate for everyone, especially if you have a good understanding of how to implement a fix or feature.
        See the Ultralytics [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!
