# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv pip install --system -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Test test_prediction.py syntax
        run: |
          python -m py_compile test_prediction.py
          python test_prediction.py --help

      - name: Test prediction script
        run: |
          # Test Python import works
          python -c "from yolo11n.predict import Predictor; print('yolo11n predictor import OK')"
        continue-on-error: true

      - name: Validate Cog configuration
        run: |
          # Check YAML syntax
          python -c "import yaml; yaml.safe_load(open('yolo11n/cog.yaml')); print('yolo11n cog.yaml valid')"
