name: Push YOLO to Replicate

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      model_dir:
        description: 'Model directory (e.g. "yolo11n" or "custom")'
        required: true
        default: "yolo11n"

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup disk space
        uses: ultralytics/actions/cleanup-disk@main

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Download YOLO11n weights
        if: ${{ (inputs.model_dir || 'yolo11n') == 'yolo11n' }}
        run: |
          uv pip install --system ultralytics
          python -c "from ultralytics import YOLO; YOLO('yolo11n.pt').export(format='onnx', optimize=True, dynamic=True)"
          mv yolo11n.pt yolo11n.onnx yolo11n/

      - name: Push to Replicate
        run: |
          cd ${{ inputs.model_dir || 'yolo11n' }}
          cog push
