name: Push YOLO to Replicate

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Model name (e.g. "ultralytics/yolo11n")'
        required: true
        default: "ultralytics/yolo11n"
      model_dir:
        description: 'Model directory (e.g. "yolo11n" or "custom")'
        required: true
        default: "yolo11n"

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup disk space
        uses: ultralytics/actions/cleanup-disk@main

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Push to Replicate
        run: |
          cd ${{ inputs.model_dir || 'yolo11n' }}
          cog push r8.im/${{ inputs.model_name || 'ultralytics/yolo11n' }}
