name: Push YOLO to Replicate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup disk space
        uses: ultralytics/actions/cleanup-disk@main

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv pip install --system ultralytics --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Download YOLO11n weights
          python -c "from ultralytics import YOLO; YOLO('yolo11n.pt').export(format='onnx', optimize=True, dynamic=True)"
          mv yolo11n.pt yolo11n.onnx yolo11n/

      - name: Push to Replicate
        run: |
          cd yolo11n
          cog push
