name: Push All YOLO Models

on:
  push:
    branches: [main]
    paths:
      - 'yolo11n/**'
      - 'custom/**'
  workflow_dispatch:

jobs:
  push_models:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dir: yolo11n
            model: ultralytics/yolo11n
          - dir: custom  
            model: your-username/your-custom-model
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}
          
      - name: Push to Replicate
        run: |
          cd ${{ matrix.dir }}
          cog push r8.im/${{ matrix.model }}
