name: Push YOLO11n to Replicate

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      #- name: Cleanup disk space
      #  uses: ultralytics/actions/cleanup-disk@main

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv pip install --system -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Download YOLO11n weights
        run: |
          python << 'EOF'
          from ultralytics import YOLO
          model = YOLO('yolo11n.pt')
          model.export(format='onnx', optimize=True, dynamic=True)
          EOF
          mv yolo11n.pt yolo11n.onnx yolo11n/

      - name: Push to Replicate
        run: |
          cd yolo11n
          cog push
